workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.example.activeEcommerceSellerApp
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Clean build directory
        script: flutter clean
      - name: Build IPA
        script: |
          flutter build ipa --release --export-method app-store
          # List the contents of the IPA directory to verify
          ls -la build/ios/ipa/
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true