// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwpEfFQszIXSyoAzYIImAzbQBKbBC-tnQ',
    appId: '1:522961363699:android:647524f830e1499a468d86',
    messagingSenderId: '522961363699',
    projectId: 'jomlahcom',
    databaseURL: 'https://jomlahcom.firebaseio.com',
    storageBucket: 'jomlahcom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaIkDgdR8huAm3NSYtoL-jCDzb58Ppo00',
    appId: '1:522961363699:ios:77797f37b22f999d468d86',
    messagingSenderId: '522961363699',
    projectId: 'jomlahcom',
    databaseURL: 'https://jomlahcom.firebaseio.com',
    storageBucket: 'jomlahcom.firebasestorage.app',
    androidClientId: '522961363699-m9is9hklednt5ipktna90c9kbisuo6d2.apps.googleusercontent.com',
    iosClientId: '522961363699-74aira7t81qopt9dp85iqperb4u966g0.apps.googleusercontent.com',
    iosBundleId: 'com.example.activeEcommerceSellerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaIkDgdR8huAm3NSYtoL-jCDzb58Ppo00',
    appId: '1:522961363699:ios:77797f37b22f999d468d86',
    messagingSenderId: '522961363699',
    projectId: 'jomlahcom',
    databaseURL: 'https://jomlahcom.firebaseio.com',
    storageBucket: 'jomlahcom.firebasestorage.app',
    androidClientId: '522961363699-m9is9hklednt5ipktna90c9kbisuo6d2.apps.googleusercontent.com',
    iosClientId: '522961363699-74aira7t81qopt9dp85iqperb4u966g0.apps.googleusercontent.com',
    iosBundleId: 'com.example.activeEcommerceSellerApp',
  );
}
